# Generated by Django 2.2.17 on 2021-02-01 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estructura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fantasma',
            fields=[
                ('uid', models.CharField(max_length=30)),
                ('votos', models.IntegerField(null=True)),
                ('origen', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='votacion',
            fields=[
                ('cod', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('acta', models.IntegerField(null=True)),
                ('sufragantes', models.IntegerField(null=True)),
                ('blancos', models.IntegerField(null=True)),
                ('nulos', models.IntegerField(null=True)),
                ('delegados', models.IntegerField(null=True)),
                ('app_digitacion', models.IntegerField(null=True)),
                ('conteo_rapido_cne', models.IntegerField(null=True)),
                ('digitalizacion_cne', models.IntegerField(null=True)),
                ('cne1', models.IntegerField(null=True)),
                ('ocr_nuestro_actas_cne', models.IntegerField(null=True)),
                ('cne2', models.IntegerField(null=True)),
                ('cne3', models.IntegerField(null=True)),
                ('cne4', models.IntegerField(null=True)),
                ('diff1', models.IntegerField(null=True)),
                ('diff2', models.IntegerField(null=True)),
                ('diff3', models.IntegerField(null=True)),
                ('diff4', models.IntegerField(null=True)),
                ('canton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.Canton')),
                ('circunscripcion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estructura.Circunscripcion')),
                ('dignidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.dignidad')),
                ('jrv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.JRV')),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.Parroquia')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.partido')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.Provincia')),
                ('recinto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.Recinto')),
                ('zona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estructura.Zona')),
            ],
            options={
                'ordering': ['cod'],
            },
        ),
    ]
