# Generated by Django 2.2.16 on 2021-03-18 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparacion', '0002_auto_20210312_1706'),
    ]

    operations = [
        migrations.DeleteModel(
            name='votacion',
        ),
    ]
