# Generated by Django 2.2.17 on 2021-02-01 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canton',
            fields=[
                ('codcanton', models.IntegerField(primary_key=True, serialize=False)),
                ('nomcanton', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Circunscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codcircunscripcion', models.IntegerField()),
                ('nomcircunscripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='dignidad',
            fields=[
                ('coddignidad', models.IntegerField(primary_key=True, serialize=False)),
                ('nomdignidad', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('codparroquia', models.IntegerField(primary_key=True, serialize=False)),
                ('nomparroquia', models.CharField(max_length=255)),
                ('canton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.Canton')),
                ('circunscripcion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estructura.Circunscripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('codprovincia', models.IntegerField(primary_key=True, serialize=False)),
                ('nomprovincia', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codzona', models.IntegerField()),
                ('nomzona', models.CharField(max_length=255)),
                ('circunscripcion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estructura.Circunscripcion')),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.Parroquia')),
            ],
        ),
        migrations.CreateModel(
            name='Recinto',
            fields=[
                ('codrecinto', models.IntegerField(primary_key=True, serialize=False)),
                ('nomrecinto', models.CharField(max_length=255)),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.Parroquia')),
                ('zona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estructura.Zona')),
            ],
        ),
        migrations.CreateModel(
            name='partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codpartido', models.CharField(max_length=30)),
                ('nompartido', models.CharField(max_length=255)),
                ('dignidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.dignidad')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.Provincia')),
            ],
        ),
        migrations.CreateModel(
            name='JRV',
            fields=[
                ('cod', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('codcne', models.IntegerField(null=True)),
                ('numero', models.IntegerField()),
                ('genero', models.CharField(max_length=1)),
                ('num_electores', models.IntegerField()),
                ('appsufragantes', models.IntegerField(null=True)),
                ('appblancos', models.IntegerField(null=True)),
                ('appnulos', models.IntegerField(null=True)),
                ('digitasufragantes', models.IntegerField(null=True)),
                ('digitablancos', models.IntegerField(null=True)),
                ('digitanulos', models.IntegerField(null=True)),
                ('cnesufragantes', models.IntegerField(null=True)),
                ('cneblancos', models.IntegerField(null=True)),
                ('cnenulos', models.IntegerField(null=True)),
                ('tmpdiff1', models.IntegerField(null=True)),
                ('tmpdiff2', models.IntegerField(null=True)),
                ('maxdiff', models.IntegerField(null=True)),
                ('maxdiffnal', models.IntegerField(null=True)),
                ('maxdiffprov', models.IntegerField(null=True)),
                ('maxdiffand', models.IntegerField(null=True)),
                ('para_validar', models.BooleanField(default=False)),
                ('para_validar7', models.BooleanField(default=False)),
                ('para_validar8', models.BooleanField(default=False)),
                ('para_validar9', models.BooleanField(default=False)),
                ('no_procede', models.BooleanField(default=False)),
                ('para_reclamar', models.BooleanField(default=False)),
                ('incidencia', models.BooleanField(default=False)),
                ('fecha_incidencia', models.DateTimeField(null=True)),
                ('incidencia_grave', models.BooleanField(default=False)),
                ('incidencia_resuelta', models.BooleanField(null=True)),
                ('observaciones', models.TextField()),
                ('telefonos', models.TextField()),
                ('acta_delegados', models.CharField(max_length=255, null=True)),
                ('acta_copia', models.CharField(max_length=255, null=True)),
                ('acta_cne', models.CharField(max_length=255, null=True)),
                ('noactapre', models.IntegerField(null=True)),
                ('noactanal', models.IntegerField(null=True)),
                ('noactapro', models.IntegerField(null=True)),
                ('noactaand', models.IntegerField(null=True)),
                ('canton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.Canton')),
                ('circunscripcion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estructura.Circunscripcion')),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.Parroquia')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.Provincia')),
                ('recinto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.Recinto')),
                ('zona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estructura.Zona')),
            ],
        ),
        migrations.AddField(
            model_name='circunscripcion',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.Provincia'),
        ),
        migrations.AddField(
            model_name='canton',
            name='circunscripcion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estructura.Circunscripcion'),
        ),
        migrations.AddField(
            model_name='canton',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.Provincia'),
        ),
    ]
