# Generated by Django 2.2.17 on 2021-02-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='codpartido',
            field=models.IntegerField(max_length=30),
        ),
    ]
