# Generated by Django 2.2.17 on 2021-02-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0002_auto_20210201_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='codpartido',
            field=models.IntegerField(),
        ),
    ]
