# Generated by Django 2.2.17 on 2021-02-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0003_auto_20210201_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='jrv',
            name='difnum1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jrv',
            name='difnum7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jrv',
            name='difnum8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jrv',
            name='difnum9',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jrv',
            name='otro1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jrv',
            name='otro7',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jrv',
            name='otro8',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jrv',
            name='otro9',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
