# Generated by Django 2.2.17 on 2021-02-02 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0005_auto_20210201_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='jrv',
            name='no_procede7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jrv',
            name='no_procede8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jrv',
            name='no_procede9',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jrv',
            name='para_reclamar7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jrv',
            name='para_reclamar8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jrv',
            name='para_reclamar9',
            field=models.BooleanField(default=False),
        ),
    ]
