# Generated by Django 2.2.17 on 2021-02-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0006_auto_20210201_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='jrv',
            name='pusieron',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='jrv',
            name='pusieron7',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='jrv',
            name='pusieron8',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='jrv',
            name='pusieron9',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='jrv',
            name='quitaron',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='jrv',
            name='quitaron7',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='jrv',
            name='quitaron8',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='jrv',
            name='quitaron9',
            field=models.IntegerField(null=True),
        ),
    ]
