# Generated by Django 2.2.17 on 2021-02-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0007_auto_20210204_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='jrv',
            name='acta_copia2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jrv',
            name='acta_copia3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jrv',
            name='acta_copiaand2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jrv',
            name='acta_copiaand3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jrv',
            name='acta_copianal2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jrv',
            name='acta_copianal3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jrv',
            name='acta_copiaprov2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jrv',
            name='acta_copiaprov3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jrv',
            name='acta_delegados2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jrv',
            name='acta_delegados3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jrv',
            name='acta_delegadosand2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jrv',
            name='acta_delegadosand3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jrv',
            name='acta_delegadosnal2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jrv',
            name='acta_delegadosnal3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jrv',
            name='acta_delegadosprov2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jrv',
            name='acta_delegadosprov3',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
