# Generated by Django 2.2.16 on 2021-03-12 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0008_auto_20210205_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canton',
            options={'verbose_name': 'Cantón', 'verbose_name_plural': 'Cantones'},
        ),
        migrations.AlterModelOptions(
            name='circunscripcion',
            options={'verbose_name': 'Circunscripción', 'verbose_name_plural': 'Circunscripciones'},
        ),
        migrations.AlterModelOptions(
            name='dignidad',
            options={'verbose_name': 'Dignidad', 'verbose_name_plural': 'Dignidades'},
        ),
        migrations.AlterModelOptions(
            name='jrv',
            options={'verbose_name': 'JRV', 'verbose_name_plural': 'JRVs'},
        ),
        migrations.AlterModelOptions(
            name='parroquia',
            options={'verbose_name': 'Parroquia', 'verbose_name_plural': 'Parroquias'},
        ),
        migrations.AlterModelOptions(
            name='partido',
            options={'verbose_name': 'Partido', 'verbose_name_plural': 'Partidos'},
        ),
        migrations.AlterModelOptions(
            name='provincia',
            options={'verbose_name': 'Provincia', 'verbose_name_plural': 'Provincias'},
        ),
        migrations.AlterModelOptions(
            name='recinto',
            options={'verbose_name': 'Recinto', 'verbose_name_plural': 'Recintos'},
        ),
        migrations.AlterModelOptions(
            name='zona',
            options={'verbose_name': 'Zona', 'verbose_name_plural': 'Zonas'},
        ),
    ]
