# Generated by Django 2.2.18 on 2021-03-27 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0011_auto_20210318_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='jrv',
            name='arauz_votes_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jrv',
            name='blank_votes_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jrv',
            name='max_total_votes_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jrv',
            name='null_votes_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jrv',
            name='suffragettes_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jrv',
            name='suffragettes_first_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jrv',
            name='suffragettes_votes_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jrv',
            name='unes_cne_alert',
            field=models.BooleanField(default=False),
        ),
    ]
