# Generated by Django 2.2.16 on 2021-03-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0011_auto_20210318_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
            },
        ),
        migrations.AddField(
            model_name='jrv',
            name='alerts',
            field=models.ManyToManyField(to='estructura.Alert'),
        ),
    ]
