# Generated by Django 2.2.17 on 2021-02-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='delegados',
            fields=[
                ('uid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('votos', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='digitacion_nuestra',
            fields=[
                ('uid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('votos', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='escrutinio1',
            fields=[
                ('uid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('cod_junta', models.IntegerField(null=True)),
                ('sufragantes', models.IntegerField(null=True)),
                ('blancos', models.IntegerField(null=True)),
                ('nulos', models.IntegerField(null=True)),
                ('votos', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='escrutinio2',
            fields=[
                ('uid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('votos', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='escrutinio3',
            fields=[
                ('uid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('votos', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='escrutinio4',
            fields=[
                ('uid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('votos', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='preconteo',
            fields=[
                ('uid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('votos', models.IntegerField(null=True)),
            ],
        ),
    ]
