# Generated by Django 2.2.16 on 2021-03-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escrutinio1',
            old_name='votos',
            new_name='arauz_votes',
        ),
        migrations.AddField(
            model_name='escrutinio1',
            name='lasso_votes',
            field=models.IntegerField(null=True),
        ),
    ]
