# Generated by Django 2.2.16 on 2021-03-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmp', '0002_auto_20210318_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='aplicacion',
            fields=[
                ('uid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('cod_junta', models.IntegerField(null=True)),
                ('sufragantes', models.IntegerField(null=True)),
                ('blancos', models.IntegerField(null=True)),
                ('nulos', models.IntegerField(null=True)),
                ('arauz_votes', models.IntegerField(null=True)),
                ('lasso_votes', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='old_cne',
            fields=[
                ('uid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('cod_junta', models.IntegerField(null=True)),
                ('sufragantes', models.IntegerField(null=True)),
                ('blancos', models.IntegerField(null=True)),
                ('nulos', models.IntegerField(null=True)),
                ('arauz_votes', models.IntegerField(null=True)),
                ('lasso_votes', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='delegados',
        ),
        migrations.DeleteModel(
            name='digitacion_nuestra',
        ),
        migrations.DeleteModel(
            name='preconteo',
        ),
        migrations.RenameField(
            model_name='escrutinio2',
            old_name='votos',
            new_name='arauz_votes',
        ),
        migrations.RenameField(
            model_name='escrutinio3',
            old_name='votos',
            new_name='arauz_votes',
        ),
        migrations.RenameField(
            model_name='escrutinio4',
            old_name='votos',
            new_name='arauz_votes',
        ),
        migrations.AddField(
            model_name='escrutinio2',
            name='blancos',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='escrutinio2',
            name='cod_junta',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='escrutinio2',
            name='lasso_votes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='escrutinio2',
            name='nulos',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='escrutinio2',
            name='sufragantes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='escrutinio3',
            name='blancos',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='escrutinio3',
            name='cod_junta',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='escrutinio3',
            name='lasso_votes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='escrutinio3',
            name='nulos',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='escrutinio3',
            name='sufragantes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='escrutinio4',
            name='blancos',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='escrutinio4',
            name='cod_junta',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='escrutinio4',
            name='lasso_votes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='escrutinio4',
            name='nulos',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='escrutinio4',
            name='sufragantes',
            field=models.IntegerField(null=True),
        ),
    ]
